# Generated by Django 4.0.1 on 2022-02-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название страны')),
                ('population', models.CharField(max_length=20, verbose_name='Насиление')),
                ('presidents', models.CharField(max_length=20, verbose_name='Президент')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
